### PR TITLE
Update k8s dependencies to v0.32.2

### PR DESCRIPTION
**Pull request by naemono**
I didn't want to contribute/commit directly to https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/193, but the reason the PR is failing is because of https://github.com/kubernetes/kubernetes/pull/128196/files (`k8s.io/apiserver/pkg/util/version` was renamed to `k8s.io/component-base/version`).

This should both upgrade the deps, and resolve the failing import issue.

Feel free to either accept this PR, or simply update the previous PR. (cc @dgrisonnet)

### CODE REVIEW

**Comment by naemono** [comment]
I replicated the golangci-lint errors locally:
```
❯ ~/.asdf/installs/golang/1.23.6/packages/bin/golangci-lint run --modules-download-mode=readonly --timeout 10m
WARN [runner/nolint] Found unknown linters in //nolint directives: logcheck
test-adapter/provider/provider.go:120:103: undefined: restful (typecheck)
func NewFakeProvider(client dynamic.Interface, mapper apimeta.RESTMapper) (provider.MetricsProvider, *restful.WebService) {
                                                                                                      ^
test-adapter/provider/provider.go:134:41: undefined: restful (typecheck)
func (p *testingProvider) webService() *restful.WebService {
```

which seems to be related to the version of golangci-lint, as upgrading to the version prior to go 1.24 support fixes the issue, but brought up more linting issues.

```
❯ ~/.asdf/installs/golang/1.23.6/packages/bin/golangci-lint run --modules-download-mode=readonly --timeout 10m
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
test-adapter/main.go:78:13: printf: non-constant format string in call to k8s.io/klog/v2.Infof (govet)
        klog.Infof(cmd.Message)
                   ^
pkg/apiserver/installer/apiserver_test.go:303:13: printf: non-constant format string in call to (*testing.common).Errorf (govet)
                        t.Errorf(err.Error())
                                 ^
pkg/apiserver/installer/apiserver_test.go:345:13: printf: non-constant format string in call to (*testing.common).Errorf (govet)
                        t.Errorf(err.Error())
```

Which I have additionally resolved in https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/194/commits/5606f1f9f35a0b4e742fa379a0e0e4c4cd5d14e1.

**Comment by naemono** [comment]
`s/deadline/timeout`: https://github.com/golangci/golangci-lint/pull/822

**Comment by naemono** [comment]
(feels like a rabbit-hole I'm going down here) I also had to update openapi generated file(s) in https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/194/commits/13670a5563802178fc666b6437e661169326b038

**Review by RainbowMango — COMMENTED** [review]
/assign

File: Makefile [hunk 1]
```diff
@@ -7,7 +7,7 @@ GOPATH:=$(shell go env GOPATH)
 
 VERSION?=latest
 
-GOLANGCI_VERSION:=1.55.2
+GOLANGCI_VERSION:=1.63.4
```
Comment (RainbowMango) [inline Makefile:10]: It looks good to me. 
Just out of curiosity, is it the mandatory thing to bump golangci-lint?

**Review by RainbowMango — COMMENTED** [review]
Thank you @naemono for doing this.
/lgtm

It saves the effort to update the previous PR sent by the dependent robot.

File: Makefile (hunk 1 above)
Comment (naemono) [reply Makefile:10]: Yes, it was throwing all sorts of errors in previous ci runs.

**Comment by naemono** [comment]
> By the way, it would be great to quash the commits for clean history.

I can do this. No worries.

File: Makefile (hunk 1 above)
Comment (RainbowMango) [reply Makefile:10]: Thanks, got it.

**Comment by RainbowMango** [comment]
/lgtm

Let's wait approval from @dgrisonnet .

Just a reminder, please consider if you need to tag new releases before(v1.31.0) and after(v1.32.0) this PR.

**Comment by barkbay** [comment]
Hey team 👋 , any update on this one 🙏 , thanks!

**Comment by dgrisonnet** [comment]
I'll try to get some time to do a 1.31 release and then I'll merge this PR

**Comment by RainbowMango** [comment]
Kindly ping @dgrisonnet ~ Thanks.
I'm currently waiting this PR~

**Comment by RainbowMango** [comment]
Great thanks!
